<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18661" started-at="2021-10-03T01:31:42 EET" finished-at="2021-10-03T01:32:01 EET">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18661" started-at="2021-10-03T01:31:42 EET" finished-at="2021-10-03T01:32:01 EET">
      <class name="Testing.TC1">
        <test-method status="PASS" signature="BasicSetUp()[pri:0, instance:Testing.TC1@694e1548]" name="BasicSetUp" is-config="true" duration-ms="5092" started-at="2021-10-03T01:31:42 EET" finished-at="2021-10-03T01:31:47 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BasicSetUp -->
        <test-method status="FAIL" signature="T1()[pri:0, instance:Testing.TC1@694e1548]" name="T1" duration-ms="13412" started-at="2021-10-03T01:31:47 EET" finished-at="2021-10-03T01:32:01 EET">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The Total Price is Greater than 75 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The Total Price is Greater than 75 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at Testing.TC1.T1(TC1.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- T1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Testing.TC1@694e1548]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-10-03T01:32:01 EET" finished-at="2021-10-03T01:32:01 EET">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Testing.TC1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
